# Generated by Django 5.0.4 on 2024-04-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0012_groupuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupUser',
        ),
    ]
